language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - env: MAGENTO_VERSION=magento-ce-1.9.1.0
  - php: 5.3
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.2
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.1
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.0
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
env:
  - APPNAME=Ffuenf_Pagespeed
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy: .travis/bundle.sh
deploy:
  provider: releases
  file:
    - "Ffuenf_Pagespeed.zip"
    - "Ffuenf_Pagespeed.tar.gz"
  skip_cleanup: true
  on:
    branch: dev
